# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x0cmlservice.v1\"\x0f\n\rHealthRequest\"7\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\"\x9e\x02\n\x0ePredictRequest\x12\x0f\n\x07\x61lcohol\x18\x01 \x01(\x01\x12\x12\n\nmalic_acid\x18\x02 \x01(\x01\x12\x0b\n\x03\x61sh\x18\x03 \x01(\x01\x12\x19\n\x11\x61lcalinity_of_ash\x18\x04 \x01(\x01\x12\x11\n\tmagnesium\x18\x05 \x01(\x01\x12\x15\n\rtotal_phenols\x18\x06 \x01(\x01\x12\x12\n\nflavanoids\x18\x07 \x01(\x01\x12\x1c\n\x14nonflavanoid_phenols\x18\x08 \x01(\x01\x12\x17\n\x0fproanthocyanins\x18\t \x01(\x01\x12\x17\n\x0f\x63olor_intensity\x18\n \x01(\x01\x12\x0b\n\x03hue\x18\x0b \x01(\x01\x12\x13\n\x0bod280_od315\x18\x0c \x01(\x01\x12\x0f\n\x07proline\x18\r \x01(\x01\"9\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x32\xa0\x01\n\x11PredictionService\x12\x43\n\x06Health\x12\x1b.mlservice.v1.HealthRequest\x1a\x1c.mlservice.v1.HealthResponse\x12\x46\n\x07Predict\x12\x1c.mlservice.v1.PredictRequest\x1a\x1d.mlservice.v1.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=29
  _globals['_HEALTHREQUEST']._serialized_end=44
  _globals['_HEALTHRESPONSE']._serialized_start=46
  _globals['_HEALTHRESPONSE']._serialized_end=101
  _globals['_PREDICTREQUEST']._serialized_start=104
  _globals['_PREDICTREQUEST']._serialized_end=390
  _globals['_PREDICTRESPONSE']._serialized_start=392
  _globals['_PREDICTRESPONSE']._serialized_end=449
  _globals['_PREDICTIONSERVICE']._serialized_start=452
  _globals['_PREDICTIONSERVICE']._serialized_end=612
# @@protoc_insertion_point(module_scope)
